---
# handlers file for etcd-cluster

# Restart primarys one-by-one to keep quorum
- name: restart etcd primarys
  become: yes
  become_user: root
  service:
    name: etcd
    state: restarted
  run_once: yes
  loop: "{{ groups['all'] }}"
  delegate_to: '{{ item }}'
  when:
  - etcd_launch | bool
  - hostvars[inventory_hostname].etcd_primary | bool

# Restart non-voting members
- name: restart etcd members
  become: yes
  become_user: root
  when:
  - etcd_launch | bool
  - not hostvars[inventory_hostname].etcd_primary | bool
  service:
    name: etcd
    state: restarted
